Fix $0 parsing.

diff --git a/dbgsym-recompress b/dbgsym-recompress
--- a/dbgsym-recompress
+++ b/dbgsym-recompress
@@ -7,12 +7,12 @@ set -e -u
 UID=$(id -u)
 if [ $# != 2 ]
 then
-    printf 'Usage: %s IN-DEB OUT-DEB\n' "${0#**/}" >&2
+    printf 'Usage: %s IN-DEB OUT-DEB\n' "${0##*/}" >&2
     exit 1
 fi
 if [ "$UID" -ne 0 ]
 then
-    printf '%s: error: must be run as (fake)root\n' "${0#**/}" >&2
+    printf '%s: error: must be run as (fake)root\n' "${0##*/}" >&2
     exit 1
 fi
 in="$1"
